param(
  [string]$Version = "0.1.0"
)

$ErrorActionPreference = "Stop"

$repoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..\..")).Path
$distRoot = Join-Path $repoRoot "dist"
$packageName = "SWCAD-Workflow-$Version"
$packageRoot = Join-Path $distRoot $packageName
$zipPath = Join-Path $distRoot "$packageName.zip"
$checksumPath = "$zipPath.sha256"

if ($Version -notmatch '^[0-9A-Za-z][0-9A-Za-z._-]*$') {
  throw "Invalid package version: $Version"
}

$distFull = [IO.Path]::GetFullPath($distRoot).TrimEnd([IO.Path]::DirectorySeparatorChar)
$packageFull = [IO.Path]::GetFullPath($packageRoot)
$zipFull = [IO.Path]::GetFullPath($zipPath)
$checksumFull = [IO.Path]::GetFullPath($checksumPath)
$distPrefix = $distFull + [IO.Path]::DirectorySeparatorChar
if (-not $packageFull.StartsWith($distPrefix, [StringComparison]::OrdinalIgnoreCase)) {
  throw "Package directory escaped dist: $packageFull"
}
if (-not $zipFull.StartsWith($distPrefix, [StringComparison]::OrdinalIgnoreCase)) {
  throw "Package archive escaped dist: $zipFull"
}
if (-not $checksumFull.StartsWith($distPrefix, [StringComparison]::OrdinalIgnoreCase)) {
  throw "Package checksum escaped dist: $checksumFull"
}

$files = @(
  "apps\swcad-workflow\swcad_workflow_load.lsp",
  "apps\swcad-workflow\swcad_workflow.lsp",
  "apps\swcad-workflow\README.md",
  "docs\swcad-workflow\architecture.md",
  "docs\swcad-workflow\test-results-2026-07-13.md",
  "docs\swcad-workflow\source-layout-cleanup-test-2026-07-14.md",
  "docs\swcad-workflow\full-unused-definition-cleanup-test-2026-07-14.md",
  "src\tools\gmtitle\swcad_title_scale.lsp",
  "src\tools\gmtitle\swtitle_gmtitle_dialog_autoselect.ps1",
  "src\tools\gstarcad-dimstyle\gstarcad_dimstyle_keep_tolerance.lsp",
  "src\tools\gstarcad-layout\gstarcad_layout_from_model.lsp"
)

[void](New-Item -ItemType Directory -Path $distFull -Force)
Remove-Item -LiteralPath $packageFull -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath $zipFull -Force -ErrorAction SilentlyContinue
Remove-Item -LiteralPath $checksumFull -Force -ErrorAction SilentlyContinue
[void](New-Item -ItemType Directory -Path $packageRoot -Force)

foreach ($relative in $files) {
  $source = Join-Path $repoRoot $relative
  if (-not (Test-Path -LiteralPath $source)) {
    throw "Package source is missing: $relative"
  }
  $destination = Join-Path $packageRoot $relative
  [void](New-Item -ItemType Directory -Path (Split-Path -Parent $destination) -Force)
  Copy-Item -LiteralPath $source -Destination $destination -Force
}

$installerPowerShell = @'
$ErrorActionPreference = "Stop"

$packageRoot = (Resolve-Path -LiteralPath $PSScriptRoot).Path
$loaderPath = Join-Path $packageRoot "SWCAD_Workflow_Load.lsp"
$rootForLisp = $packageRoot.Replace("\", "/")
$lines = @(
  ";;; Generated by install.ps1. Rerun the installer after moving this package.",
  "(vl-load-com)",
  "(setenv `"SWCAD_WORKFLOW_ROOT`" `"$rootForLisp`")",
  "(load `"$rootForLisp/apps/swcad-workflow/swcad_workflow_load.lsp`")",
  "(princ)"
)
[IO.File]::WriteAllLines($loaderPath, $lines, [Text.UTF8Encoding]::new($false))
Write-Output "SWCAD Workflow loader created: $loaderPath"
'@
$installerBatch = @'
@echo off
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0install.ps1"
if errorlevel 1 (
  echo SWCAD Workflow installation failed.
) else (
  echo APPLOAD the generated SWCAD_Workflow_Load.lsp file in GstarCAD Mechanical.
)
pause
'@
[IO.File]::WriteAllText((Join-Path $packageFull "install.ps1"), $installerPowerShell, [Text.UTF8Encoding]::new($false))
[IO.File]::WriteAllText((Join-Path $packageFull "Install_SWCAD_Workflow.cmd"), $installerBatch, [Text.Encoding]::ASCII)

Compress-Archive -LiteralPath $packageRoot -DestinationPath $zipPath -CompressionLevel Optimal
$zipHash = (Get-FileHash -LiteralPath $zipFull -Algorithm SHA256).Hash
[IO.File]::WriteAllText(
  $checksumFull,
  "$zipHash *$([IO.Path]::GetFileName($zipFull))`r`n",
  [Text.Encoding]::ASCII
)
Write-Output "SWCAD Workflow package created: $zipPath"
Write-Output "SWCAD Workflow checksum created: $checksumPath"
